"""customer_churn_business_ml.ipynb

Automatically generated by Colab.

!unzip *.zip

import pandas as pd

df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

df.head()

df.shape

df.info()

df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

df.isnull().sum()

df["TotalCharges"].fillna(df["TotalCharges"].median(), inplace=True)

df['Churn'].value_counts()

df.drop(columns=['customerID'], inplace=True)

df.groupby('Contract')['Churn'].value_counts(normalize=True)

import seaborn as sns
sns.boxplot(x='Churn', y='MonthlyCharges', data=df)

df_encoded = pd.get_dummies(df, drop_first=True)

from sklearn.model_selection import train_test_split

X = df_encoded.drop('Churn_Yes', axis=1)
y = df_encoded['Churn_Yes']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

from sklearn.metrics import classification_report, roc_auc_score

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred))
roc_auc_score(y_test, y_prob)

def retention_action(prob):
    if prob > 0.7:
        return "Offer discount / Call customer"
    elif prob > 0.4:
        return "Send loyalty email"
    else:
        return "Upsell / No action needed"

results = X_test.copy()
results['churn_probability'] = y_prob
results['risk_level'] = results['churn_probability'].apply(retention_action)
results.head()

pip install streamlit

# Only if CSV not yet created
results['churn_probability'] = y_prob
results['risk_category'] = results['churn_probability'].apply(retention_action)
results.to_csv("churn_predictions.csv", index=False)

df = pd.read_csv("churn_predictions.csv")
